theme: null
title: "Aprovados AFT 2024"
description: "Comissão de Aprovados no Cadastro de Reserva do concurso para Auditor-Fiscal do Trabalho."
url: "https://aprovadosaft2024.com"
plugins:
  - jekyll-sitemap
